# Matrices Identidad, Inversa y Singular

In [1]:
import numpy as np

In [2]:
# Matriz Identidad
identidad = np.eye(4)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
vector = np.array([[2], [3], [5], [7]])
print(vector)

[[2]
 [3]
 [5]
 [7]]


In [4]:
 # Identidad * Vector = Vector
# La matriz identidad es el elemento neutro en las matrices

print(identidad.dot(vector))

[[2.]
 [3.]
 [5.]
 [7.]]


### Inversa

In [5]:
A = np.array([[1, 0, 1], [0, 1, 1], [-1, 1, 1]])
print(A)

[[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]


In [6]:
np.linalg.inv(A)

array([[ 0.,  1., -1.],
       [-1.,  2., -1.],
       [ 1., -1.,  1.]])

In [8]:
# Devuelve la identidad: Matriz * Su_Inversa
print(A.dot(np.linalg.inv(A)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Matriz Singular

+ Cuando no hay la inversa se llama matriz singualar

In [11]:
singular = np.array([[1, 1], [1, 1]])
print(singular)

[[1 1]
 [1 1]]


In [13]:
# Error
# np.linalg.inv(singular)