# Aplicación de la inversa de una matriz para resolver un sistema de ecuaciones lineales

In [2]:
import numpy as np

In [4]:
# Si tengo un número cercano a 0 que no me muestre todos los dicimales
np.set_printoptions(suppress=True)

In [5]:
A = np.array([[3, 1], [2, 1]])
A

array([[3, 1],
       [2, 1]])

In [6]:
B = np.array([[1], [1]])
print(B)

[[1]
 [1]]


In [7]:
np.linalg.inv(A)

array([[ 1., -1.],
       [-2.,  3.]])

In [8]:
x = np.linalg.inv(A).dot(B)
print(x)

[[0.]
 [1.]]


In [9]:
A.dot(x)

array([[1.],
       [1.]])