In [1]:
import numpy as np

In [17]:
scalar = 5.65
vector = np.array([5, 9, 2])
matriz = np.array([[45, 67, 1], [11, 28, 0], [8, 14, 3], [5, 6, 0]])
tensor = np.array([
    [[34, 56, 78], [98, 34, 1], [45, 12, 53]],
    [[50, 89, 23], [1, 0, 34], [45, 29, 46]],
    [[12, 45, 23], [87, 45, 12], [17, 89, 2]]
])

In [18]:
vector.shape

(3,)

In [19]:
print(vector)

[5 9 2]


In [20]:
print(type(vector.shape))

<class 'tuple'>


In [21]:
len(vector)

3

+ **len()** devuelve menos información que el comando **shape**
+ **shape** dice que no tiene mas dimensiones
+ **len()** solo devuelve un 3

In [22]:
matriz

array([[45, 67,  1],
       [11, 28,  0],
       [ 8, 14,  3],
       [ 5,  6,  0]])

In [23]:
matriz.shape

(4, 3)

In [24]:
len(matriz)

4

In [25]:
# Devuelve la multiplicación de las dimensiones, la cantidad total de la matriz
matriz.size

12

In [29]:
tensor

array([[[34, 56, 78],
        [98, 34,  1],
        [45, 12, 53]],

       [[50, 89, 23],
        [ 1,  0, 34],
        [45, 29, 46]],

       [[12, 45, 23],
        [87, 45, 12],
        [17, 89,  2]]])

In [26]:
tensor.shape

(3, 3, 3)

In [27]:
tensor.size

27

In [28]:
len(tensor)

3