In [1]:
import numpy as np

In [33]:
scalar = 5.679
vector = np.array([3, 4, 5, 6])
matriz = np.array([[1, 2], [3, 4], [5, 6]])
tensor = np.array([
    [[45, 34, 12, 56], [23, 56, 12, 11]],
    [[45, 87, 10, 30], [31, 56, 29, 92]],
    [[33, 98, 51, 32], [49, 87, 12, 45]]
])

## Transpuesta

In [17]:
vector

array([3, 4, 5, 6])

In [18]:
vector.T

array([3, 4, 5, 6])

In [19]:
matriz

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
matriz.T

array([[1, 3, 5],
       [2, 4, 6]])

In [21]:
print(matriz.shape, matriz.T.shape, sep="-")

(3, 2)-(2, 3)


## Transposcición de un Tensor

In [22]:
tensor

array([[[45, 34, 12, 56],
        [23, 56, 12, 11]],

       [[45, 87, 10, 30],
        [31, 56, 29, 92]],

       [[33, 98, 51, 32],
        [49, 87, 12, 45]]])

In [23]:
tensor.T

array([[[45, 45, 33],
        [23, 31, 49]],

       [[34, 87, 98],
        [56, 56, 87]],

       [[12, 10, 51],
        [12, 29, 12]],

       [[56, 30, 32],
        [11, 92, 45]]])

In [24]:
print(tensor.shape, tensor.T.shape)

(3, 2, 4) (4, 2, 3)


In [25]:
matriz == matriz.T.T

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

## Suma de matrices

In [27]:
A = np.array([[1, 6, 9], [45, 6, 3], [9, 4, 2]])
B = np.array([[6, 7, 8], [2, 7, 9], [0, 5, 0]])
C = A + B

In [28]:
A

array([[ 1,  6,  9],
       [45,  6,  3],
       [ 9,  4,  2]])

In [29]:
B

array([[6, 7, 8],
       [2, 7, 9],
       [0, 5, 0]])

In [30]:
C

array([[ 7, 13, 17],
       [47, 13, 12],
       [ 9,  9,  2]])

In [31]:
matriz

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
matriz + scalar

array([[ 6.679,  7.679],
       [ 8.679,  9.679],
       [10.679, 11.679]])