In [1]:
import numpy as np

In [2]:
scalar = 5.679
vector = np.array([3, 4, 5])
matriz = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
vector

array([3, 4, 5])

In [4]:
matriz

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
matriz.T

array([[1, 3, 5],
       [2, 4, 6]])

+ Lo que pasa aquí es que el vector se sumó fila por fila a la matriz
+ Esto es broadcasting: extender la dimension de menor tamaño para completar la de mayor tamaño

In [8]:
A = vector + matriz.T

In [9]:
print(A)

[[ 4  7 10]
 [ 5  8 11]]
