Producto interno no el lo mismo que multiplicar una matriz por un vector.

In [2]:
import numpy as np

In [4]:
scalar = 5.679
vector = np.array([2, 3])
matriz = np.array([[1, 2], [3, 4], [5, 6]])

In [6]:
vector

array([2, 3])

In [7]:
matriz

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
# Broadcasting
# Matriz por vector
A = matriz * vector

In [15]:
A

array([[ 2,  6],
       [ 6, 12],
       [10, 18]])

In [16]:
# Producto interno
B = matriz.dot(vector)

In [17]:
B

array([ 8, 18, 28])

### Hay 2 formas de usar la función producto interno

In [20]:
# 1
matriz.dot(vector)

array([ 8, 18, 28])

In [21]:
# 2
np.dot(matriz, vector)

array([ 8, 18, 28])