In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
B = np.array([[2, 3], [5, 7], [11, 13]])

In [7]:
print(A)
print()
print(A.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

(4, 3)


In [8]:
print(B)
print()
print(B.shape)

[[ 2  3]
 [ 5  7]
 [11 13]]

(3, 2)


In [11]:
# Multiplicación de matrices
# Columnas == Filas
C = A.dot(B)

In [10]:
print(C)
print()
print(C.shape)

[[ 45  56]
 [ 99 125]
 [153 194]
 [207 263]]

(4, 2)
