# Propiedades del producto interno
## Asociativa

A x (B x C) = (A x B) x C

## Distributiva

A x (B + C) = (A x B) + (A x C)

## Conmutativa (Casi nunca se cumple en matrices)

A x B != B x C

In [2]:
import numpy as np

In [6]:
A = np.array([[2, 3], [5, 7], [11, 13]])
B = np.array([[1, 3], [2, 1]])
C = np.array([[3, 1], [4, 2]])

In [7]:
# Asociativa

A.dot(B.dot(C))

array([[ 60,  26],
       [145,  63],
       [295, 129]])

In [8]:
A.dot(B).dot(C)

array([[ 60,  26],
       [145,  63],
       [295, 129]])

In [9]:
# Distributiva

A.dot(B + C)

array([[ 26,  17],
       [ 62,  41],
       [122,  83]])

In [10]:
A.dot(B) + A.dot(C)

array([[ 26,  17],
       [ 62,  41],
       [122,  83]])

In [11]:
A.dot(B) + A.dot(C) == A.dot(C + B)

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [16]:
# Conmutativa

C.dot(B)

array([[ 5, 10],
       [ 8, 14]])

In [15]:
B.dot(C)

array([[15,  7],
       [10,  4]])

In [17]:
C.dot(B) == B.dot(C)

array([[False, False],
       [False, False]])

### La multiplicación de vectores si es conmutativa

In [18]:
vector = np.array([[2], [7]])
vector2 = np.array([[3], [5]])

In [20]:
vector.T.dot(vector2)

array([[41]])

In [21]:
vector2.T.dot(vector)

array([[41]])

## Multiplicación de matrices

In [22]:
Matriz = np.array([[5, 3, 7, 11], [0, 4, 0, 1]])
matriz = np.array([[3, 4], [7, 6], [0, 9], [4, 6]])

In [24]:
Matriz

array([[ 5,  3,  7, 11],
       [ 0,  4,  0,  1]])

In [25]:
matriz

array([[3, 4],
       [7, 6],
       [0, 9],
       [4, 6]])

In [23]:
Matriz.dot(matriz)

array([[ 80, 167],
       [ 32,  30]])

In [30]:
matriz.dot(Matriz)

array([[15, 25, 21, 37],
       [35, 45, 49, 83],
       [ 0, 36,  0,  9],
       [20, 36, 28, 50]])