# Transposición de Productos de Matrices

In [1]:
import numpy as np

In [2]:
A = np.array([[2, 3], [5, 7], [11, 13]])
B = np.array([[1, 3], [2, 1]])

In [6]:
print(A)
print()
print(A.shape)

[[ 2  3]
 [ 5  7]
 [11 13]]

(3, 2)


In [7]:
print(B)
print()
print(B.shape)

[[1 3]
 [2 1]]

(2, 2)


In [8]:
A.dot(B)

array([[ 8,  9],
       [19, 22],
       [37, 46]])

In [9]:
A.dot(B).T

array([[ 8, 19, 37],
       [ 9, 22, 46]])

In [16]:
B.T.dot(A.T)

array([[ 8, 19, 37],
       [ 9, 22, 46]])

In [17]:
B.T.dot(A.T) == A.dot(B).T

array([[ True,  True,  True],
       [ True,  True,  True]])